### PR TITLE
Compact parsing

### PR DESCRIPTION
**Pull request by matelich**
Addresses issue #8

### CODE REVIEW

**Comment by rubenv** [comment]
Could you make sure not to break existing tests and add a new unit test that covers your changes?

**Comment by matelich** [comment]
As a boring browser only guy, can you tell me how to run the tests?

**Comment by rubenv** [comment]
```
npm install
grunt test
```

**Comment by matelich** [comment]
So, I believe the test in question is defective and the code as well. I added some logging to readSegment and pushType and got this output for the test on master:

> m
> set position to 85,109
> set start to 85,109
> c
> pushing bezier3
> 80,114
> pushing bezier3
> 80,104
> pushing bezier3
> 90,104
> pushing bezier3
> 90,114
> z
> pushing line
> 85,109

But if we look at https://codepen.io/matelich/pen/MNEVRz we see the x never reaches 90.
On my branch the same logging yields

> m
> set position to 85,109
> set start to 85,109
> c
> pushing bezier3
> 80,114
> pushing bezier3
> 75,109
> pushing bezier3
> 80,104
> pushing bezier3
> 85,109
> z
> start and position equal 85,109 vs 85,109

Since the z does nothing, there actually are 4 segments.

**Comment by matelich** [comment]
I'll work up some test cases for my changes in the next day or two

**Comment by rubenv** [comment]
> I'll work up some test cases for my changes in the next day or two

Excellent, thanks a lot!

**Comment by matelich** [comment]
So, I'd call this done, but unfortunately, my testbed at https://codepen.io/matelich/pen/MMdexz shows some outliers. Not sure what's up there.

**Comment by rubenv** [comment]
Well, it doesn't break anything and the code looks good. Up to you whether or not you want it merged (and possibly improve later on) or keep it on hold.

Good for me.

**Comment by matelich** [comment]
Go for it, I don't think my changes caused the problems I'm seeing, I'll work more on tracking down why later.
Thanks!

**Comment by rubenv** [comment]
Thanks! Published to NPM as `1.0.23`.

**Pull request merged**
